const os=require("os")
console.log("platform:",os.platform())
console.log("cpus length:",os.cpus().length)
console.log("total memory::",os.totalmem())
console.log("free memory:",os.freemem())
console.log("host name:",os.hostname())
console.log("home dir:",os.homedir())
console.log("type:",os.type())
console.log("release:",os.release())
console.log("uptime:",os.uptime())
console.log("temp dir:",os.tmpdir())
console.log("home dir:",os.homedir())
console.log("user Info:",os.userInfo())